### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by GBCam** [Frost-Phoenix/nixos-config#10]
On the instructions it states to run the script as root. Inside the script it states not to run it as root.

It also states that git/default.nix needs to be changed when in reality that information is in git.nix

Also, I launched the script off a fresh install of the gnome ISO with no desktop, and after running the script and not seeing any errors pop up I had reboot the computer still into a no desktop environment

**Comment by Frost-Phoenix** [comment]
The instructions for the install script where false, the install script needs to be run normally (because I found out that if it is run as root, the creation of the directories and the copy of the wallpapers don't work). I also fixed the path of the git.nix file (it is the one in ./modules/home/git.nix).

Also for your problem it is kinda weird, does the rebuild run correctly ? It is supposed to take quite some time. With the current version of the install script it should ask you for root password after copying the files. Can you give more information on what happen when you run the script ?

**Comment by GBCam** [comment]
> The instructions for the install script where false, the install script needs to be run normally (because I found out that if it is run as root, the creation of the directories and the copy of the wallpapers don't work). I also fixed the path of the git.nix file (it is the one in ./modules/home/git.nix).
> 
> Also for your problem it is kinda weird, does the rebuild run correctly ? It is supposed to take quite some time. With the current version of the install script it should ask you for root password after copying the files. Can you give more information on what happen when you run the script ?

I will try another install later on today to fully clarify, have to head out at the moment but I greatly appreciate the quick reply.

**Comment by Frost-Phoenix** [comment]
Got an update ?

**Comment by Frost-Phoenix** [comment]
Closing because no update
