### ISSUE TITLE
Stuck in sway-lock

### ISSUE THREAD

**Issue by owittek** [Frost-Phoenix/nixos-config#12]
Hey, I really like the config and I have taken it as a base for my own configuration! A problem I have is that I'm stuck in sway-lock and don't know what to do. I have auto-login enabled so I'm not sure why it appears on startup and all I get is `WRONG`, `CLEARED` or a light going up on the circle.

I have not modified anything related to Hyprland yet so I'm not even sure what could cause it. My current "solution" is to disable it all together. Thanks a lot for any help you can provide!

**Comment by Frost-Phoenix** [comment]
Hi, 

So the fact that you choose auto login during the install has no effect on the config itself (because the config also define auto login as true in `modules/core/xserver.nix`) and swaylock is started by the hyprland config (line 14 in `modules/home/hyprland/config.nix`). 
Now when you see the swaylock screen you have to input your password (the one that you choose during the nixos install) and press enter at the end.
And if you want the disable the login screen you can just remove the line 14 in `modules/home/hyprland/config.nix`.

I Hope this can help you.

**Comment by owittek** [comment]
Hey! Just reactivated swaylock by uncommenting line 14 but I'm still having the same issue. I enter my password and hit enter but it says `Wrong` even though I'm pretty sure I'm able to enter 123 properly

**Comment by Frost-Phoenix** [comment]
I'm sorry but I really don't see what it can be. Maybe you need to use the root psw? idk. If it is not that I don't think I can really help you :disappointed:

**Comment by sleeyax** [comment]
Swaylock works a bit differently compared to what you might be used to. Just type your password to unlock it. No need to press enter, space or anything before or afterwards. If that doesn't work, your password is likely wrong. If you haven't lost your root password you can open a TTY session (CTRL + ALT + F4) to reset the user password.

**Comment by owittek** [comment]
It's really strange since my root pwd is the same as my user pwd, being 123. So I don't get why it wouldn't work. And if any characters are already typed in, how do I clear the input if it has no key to confirm my input?

**Comment by owittek** [comment]
Oh yeah I remember spamming backspace to clear the input. I am also using the en-us keyboard so that should be fine as well. Just to be sure I've also tried holding shift. Not sure if there's a CAPSLOCK indicator but I used keyd to remap it to ctrl/esc anyway.

**Comment by Frost-Phoenix** [comment]
close because multiple months without activity and not using swaylock at startup anymore.
