### ISSUE TITLE
Visual Studio Code 

### ISSUE THREAD

**Issue by codeskin-r** [Frost-Phoenix/nixos-config#20]
First of all, I really like the configuration you made! It's just that I can't know how to change the Visual Studio Code configuration as I want. I need help with that, I thank you very much in advance.** **

**Comment by Frost-Phoenix** [comment]
Hi, Happy you like it.

To change the vscode config you need to edit the `modules/home/vscodium.nix` file. In there you can add you extensions, configuration and keybinds. 

To make the process easier you can change your settings in vscode which will generate a new `settings.json` file from which you can take the new line and put it in the home manager config, (because vscode will not be able to save the file as it is "own" by home manager).

Hope this can help you and have fun with you config :)
